package com.thep2wking.oedldoedl.resources.init;

import java.util.ArrayList;
import java.util.List;

import com.thep2wking.oedldoedl.resources.items.catalysts.ItemChaosCatalyst;
import com.thep2wking.oedldoedl.resources.items.catalysts.ItemOedldoedlCatalyst;
import com.thep2wking.oedldoedl.resources.items.dusts.ItemBaseDust;
import com.thep2wking.oedldoedl.resources.items.dusts.ItemEnderDust;
import com.thep2wking.oedldoedl.resources.items.dusts.ItemOedldoedlDust;
import com.thep2wking.oedldoedl.resources.items.dusts.ItemSaltDust;
import com.thep2wking.oedldoedl.resources.items.dusts.ItemSaltpeterDust;
import com.thep2wking.oedldoedl.resources.items.dusts.ItemSulfurDust;
import com.thep2wking.oedldoedl.resources.items.elements.ItemBaseElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemCallaxiumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemFlofiniumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemInderiumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemKlaarsiumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemLaarsiumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemMakeriumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemOedldoedlElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemPumariumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemSharaniumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemSkorpiumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemStupidiumElement;
import com.thep2wking.oedldoedl.resources.items.elements.ItemTimofiumElement;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemBaseFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemCallaxiumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemFlofiniumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemInderiumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemKlaarsiumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemLaarsiumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemMakeriumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemOedldoedlFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemPumariumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemSharaniumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemSkorpiumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemStupidiumFragment;
import com.thep2wking.oedldoedl.resources.items.fragments.ItemTimofiumFragment;
import com.thep2wking.oedldoedl.resources.items.gems.ItemArgentoriumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemBaseGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemCallaxiumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemFlofiniumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemGremoriumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemHimejimariumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemInderiumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemKlaarsiumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemLaarsiumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemMakeriumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemOedldoedlGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemPumariumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemQuartariumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemSharaniumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemSkorpiumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemStupidiumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemTimofiumGem;
import com.thep2wking.oedldoedl.resources.items.gems.ItemToujouriumGem;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemArgentoriumIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemBaseIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemBedrockiumIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemChaosIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemDrunkiumIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemEndIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemGremoriumIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemHimejimariumIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemNetherIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemOedldoedlIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemOverworldIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemQuartariumIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemSadistiumIngot;
import com.thep2wking.oedldoedl.resources.items.ingots.ItemToujouriumIngot;
import com.thep2wking.oedldoedl.resources.items.misc.ItemBalancedClay;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemArgentoriumNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemBaseNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemBedrockiumNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemDrunkiumNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemEndNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemGremoriumNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemHimejimariumNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemNetherNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemOedldoedlNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemOverworldNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemQuartariumNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemSadistiumNugget;
import com.thep2wking.oedldoedl.resources.items.nuggets.ItemToujouriumNugget;
import com.thep2wking.oedldoedl.resources.items.shards.ItemArgentoriumShard;
import com.thep2wking.oedldoedl.resources.items.shards.ItemBaseShard;
import com.thep2wking.oedldoedl.resources.items.shards.ItemGremoriumShard;
import com.thep2wking.oedldoedl.resources.items.shards.ItemHimejimariumShard;
import com.thep2wking.oedldoedl.resources.items.shards.ItemInfinityShard;
import com.thep2wking.oedldoedl.resources.items.shards.ItemOedldoedlShard;
import com.thep2wking.oedldoedl.resources.items.shards.ItemQuartariumShard;
import com.thep2wking.oedldoedl.resources.items.shards.ItemToujouriumShard;
import com.thep2wking.oedldoedl.resources.items.singularities.ItemArgentoriumSingularity;
import com.thep2wking.oedldoedl.resources.items.singularities.ItemBaseSingularity;
import com.thep2wking.oedldoedl.resources.items.singularities.ItemGremoriumSingularity;
import com.thep2wking.oedldoedl.resources.items.singularities.ItemHimejimariumSingularity;
import com.thep2wking.oedldoedl.resources.items.singularities.ItemOedldoedlSingularity;
import com.thep2wking.oedldoedl.resources.items.singularities.ItemQuartariumSingularity;
import com.thep2wking.oedldoedl.resources.items.singularities.ItemToujouriumSingularity;
import com.thep2wking.oedldoedl.resources.items.stars.ItemBaseStar;
import com.thep2wking.oedldoedl.resources.items.stars.ItemInfinityStar;
import com.thep2wking.oedldoedl.resources.items.stars.ItemOedldoedlStar;

import net.minecraft.item.Item;

public class ItemInit 
{
	public static final List<Item> ITEMS = new ArrayList<Item>();
	
	public static final ItemBaseStar ITEM_BASE_STAR = new ItemBaseStar("base_star");
	public static final ItemOedldoedlStar ITEM_OEDLDOEDL_STAR = new ItemOedldoedlStar("oedldoedl_star");
	public static final ItemInfinityStar ITEM_INFINITY_STAR = new ItemInfinityStar("infinity_star");
	
	public static final ItemBaseIngot ITEM_BASE_INGOT = new ItemBaseIngot("base_ingot");
	public static final ItemOedldoedlIngot ITEM_OEDLDOEDL_INGOT = new ItemOedldoedlIngot("oedldoedl_ingot");
	public static final ItemBedrockiumIngot ITEM_BEDROCKIUM_INGOT = new ItemBedrockiumIngot("bedrockium_ingot");
	public static final ItemDrunkiumIngot ITEM_DRUNKIUM_INGOT = new ItemDrunkiumIngot("drunkium_ingot");
	public static final ItemSadistiumIngot ITEM_SADISTIUM_INGOT = new ItemSadistiumIngot("sadistium_ingot");
	public static final ItemOverworldIngot ITEM_OVERWORLD_INGOT = new ItemOverworldIngot("overworld_ingot");
	public static final ItemNetherIngot ITEM_NETHER_INGOT = new ItemNetherIngot("nether_ingot");
	public static final ItemEndIngot ITEM_END_INGOT = new ItemEndIngot("end_ingot");
	public static final ItemGremoriumIngot ITEM_GREMORIUM_INGOT = new ItemGremoriumIngot("gremorium_ingot");
	public static final ItemHimejimariumIngot ITEM_HIMEJIMARIUM_INGOT = new ItemHimejimariumIngot("himejimarium_ingot");
	public static final ItemToujouriumIngot ITEM_TOUJOURIUM_INGOT = new ItemToujouriumIngot("toujourium_ingot");
	public static final ItemArgentoriumIngot ITEM_ARGENTORIUM_INGOT = new ItemArgentoriumIngot("argentorium_ingot");
	public static final ItemQuartariumIngot ITEM_QUARTARIUM_INGOT = new ItemQuartariumIngot("quartarium_ingot");
	public static final ItemChaosIngot ITEM_CHAOS_INGOT = new ItemChaosIngot("chaos_ingot");
	
	public static final ItemBaseGem ITEM_BASE_GEM = new ItemBaseGem("base_gem");
	public static final ItemOedldoedlGem ITEM_OEDLDOEDL_GEM = new ItemOedldoedlGem("oedldoedl_gem");
	public static final ItemTimofiumGem ITEM_TIMOFIUM_GEM = new ItemTimofiumGem("timofium_gem");
	public static final ItemFlofiniumGem ITEM_FLOFINIUM_GEM = new ItemFlofiniumGem("flofinium_gem");
	public static final ItemLaarsiumGem ITEM_LAARSIUM_GEM = new ItemLaarsiumGem("laarsium_gem");
	public static final ItemKlaarsiumGem ITEM_KLAARSIUM_GEM = new ItemKlaarsiumGem("klaarsium_gem");
	public static final ItemSharaniumGem ITEM_SHARANIUM_GEM = new ItemSharaniumGem("sharanium_gem");
	public static final ItemMakeriumGem ITEM_MAKERIUM_GEM = new ItemMakeriumGem("makerium_gem");
	public static final ItemInderiumGem ITEM_INDERIUM_GEM = new ItemInderiumGem("inderium_gem");
	public static final ItemPumariumGem ITEM_PUMARIUM_GEM = new ItemPumariumGem("pumarium_gem");
	public static final ItemCallaxiumGem ITEM_CALLAXIUM_GEM = new ItemCallaxiumGem("callaxium_gem");
	public static final ItemSkorpiumGem ITEM_SKORPIUM_GEM = new ItemSkorpiumGem("skorpium_gem");
	public static final ItemStupidiumGem ITEM_STUPIDIUM_GEM = new ItemStupidiumGem("stupidium_gem");
	public static final ItemGremoriumGem ITEM_GREMORIUM_GEM = new ItemGremoriumGem("gremorium_gem");
	public static final ItemHimejimariumGem ITEM_HIMEJIMARIUM_GEM = new ItemHimejimariumGem("himejimarium_gem");
	public static final ItemToujouriumGem ITEM_TOUJOURIUM_GEM = new ItemToujouriumGem("toujourium_gem");
	public static final ItemArgentoriumGem ITEM_ARGENTORIUM_GEM = new ItemArgentoriumGem("argentorium_gem");
	public static final ItemQuartariumGem ITEM_QUARTARIUM_GEM = new ItemQuartariumGem("quartarium_gem");
	
	public static final ItemBaseElement ITEM_BASE_ELEMENT = new ItemBaseElement("base_element");
	public static final ItemOedldoedlElement ITEM_OEDLDOEDL_ELEMENT = new ItemOedldoedlElement("oedldoedl_element");
	public static final ItemTimofiumElement ITEM_TIMOFIUM_ELEMENT = new ItemTimofiumElement("timofium_element");
	public static final ItemFlofiniumElement ITEM_FLOFINIUM_ELEMENT = new ItemFlofiniumElement("flofinium_element");
	public static final ItemLaarsiumElement ITEM_LAARSIUM_ELEMENT = new ItemLaarsiumElement("laarsium_element");
	public static final ItemKlaarsiumElement ITEM_KLAARSIUM_ELEMENT = new ItemKlaarsiumElement("klaarsium_element");
	public static final ItemSharaniumElement ITEM_SHARANIUM_ELEMENT = new ItemSharaniumElement("sharanium_element");
	public static final ItemMakeriumElement ITEM_MAKERIUM_ELEMENT = new ItemMakeriumElement("makerium_element");
	public static final ItemInderiumElement ITEM_INDERIUM_ELEMENT = new ItemInderiumElement("inderium_element");
	public static final ItemPumariumElement ITEM_PUMARIUM_ELEMENT = new ItemPumariumElement("pumarium_element");
	public static final ItemCallaxiumElement ITEM_CALLAXIUM_ELEMENT = new ItemCallaxiumElement("callaxium_element");
	public static final ItemSkorpiumElement ITEM_SKORPIUM_ELEMENT = new ItemSkorpiumElement("skorpium_element");
	public static final ItemStupidiumElement ITEM_STUPIDIUM_ELEMENT = new ItemStupidiumElement("stupidium_element");

	public static final ItemBaseShard ITEM_BASE_SHARD = new ItemBaseShard("base_shard");
	public static final ItemOedldoedlShard ITEM_OEDLDOEDL_SHARD = new ItemOedldoedlShard("oedldoedl_shard");
	public static final ItemInfinityShard ITEM_INFINITY_SHARD = new ItemInfinityShard("infinity_shard");
	public static final ItemGremoriumShard ITEM_GREMORIUM_SHARD = new ItemGremoriumShard("gremorium_shard");
	public static final ItemHimejimariumShard ITEM_HIMEJIMARIUM_SHARD = new ItemHimejimariumShard("himejimarium_shard");
	public static final ItemToujouriumShard ITEM_TOUJOURIUM_SHARD = new ItemToujouriumShard("toujourium_shard");
	public static final ItemArgentoriumShard ITEM_ARGENTORIUM_SHARD = new ItemArgentoriumShard("argentorium_shard");
	public static final ItemQuartariumShard ITEM_QUARTARIUM_SHARD = new ItemQuartariumShard("quartarium_shard");
	
	public static final ItemBaseNugget ITEM_BASE_NUGGET = new ItemBaseNugget("base_nugget");
	public static final ItemOedldoedlNugget ITEM_OEDLDOEDL_NUGGET = new ItemOedldoedlNugget("oedldoedl_nugget");
	public static final ItemBedrockiumNugget ITEM_BEDROCKIUM_NUGGET = new ItemBedrockiumNugget("bedrockium_nugget");
	public static final ItemDrunkiumNugget ITEM_DRUNKIUM_NUGGET = new ItemDrunkiumNugget("drunkium_nugget");
	public static final ItemSadistiumNugget ITEM_SADISTIUM_NUGGET = new ItemSadistiumNugget("sadistium_nugget");
	public static final ItemOverworldNugget ITEM_OVERWORLD_NUGGET = new ItemOverworldNugget("overworld_nugget");
	public static final ItemNetherNugget ITEM_NETHER_NUGGET = new ItemNetherNugget("nether_nugget");
	public static final ItemEndNugget ITEM_END_NUGGET = new ItemEndNugget("end_nugget");
	public static final ItemGremoriumNugget ITEM_GREMORIUM_NUGGET = new ItemGremoriumNugget("gremorium_nugget");
	public static final ItemHimejimariumNugget ITEM_HIMEJIMARIUM_NUGGET = new ItemHimejimariumNugget("himejimarium_nugget");
	public static final ItemToujouriumNugget ITEM_TOUJOURIUM_NUGGET = new ItemToujouriumNugget("toujourium_nugget");
	public static final ItemArgentoriumNugget ITEM_ARGENTORIUM_NUGGET = new ItemArgentoriumNugget("argentorium_nugget");
	public static final ItemQuartariumNugget ITEM_QUARTARIUM_NUGGET = new ItemQuartariumNugget("quartarium_nugget");
	
	public static final ItemBaseFragment ITEM_BASE_FRAGMENT = new ItemBaseFragment("base_fragment");
	public static final ItemOedldoedlFragment ITEM_OEDLDOEDL_FRAGMENT = new ItemOedldoedlFragment("oedldoedl_fragment");
	public static final ItemTimofiumFragment ITEM_TIMOFIUM_FRAGMENT = new ItemTimofiumFragment("timofium_fragment");
	public static final ItemFlofiniumFragment ITEM_FLOFINIUM_FRAGMENT = new ItemFlofiniumFragment("flofinium_fragment");
	public static final ItemLaarsiumFragment ITEM_LAARSIUM_FRAGMENT = new ItemLaarsiumFragment("laarsium_fragment");
	public static final ItemKlaarsiumFragment ITEM_KLAARSIUM_FRAGMENT = new ItemKlaarsiumFragment("klaarsium_fragment");
	public static final ItemSharaniumFragment ITEM_SHARANIUM_FRAGMENT = new ItemSharaniumFragment("sharanium_fragment");
	public static final ItemMakeriumFragment ITEM_MAKERIUM_FRAGMENT = new ItemMakeriumFragment("makerium_fragment");
	public static final ItemInderiumFragment ITEM_INDERIUM_FRAGMENT = new ItemInderiumFragment("inderium_fragment");
	public static final ItemPumariumFragment ITEM_PUMARIUM_FRAGMENT = new ItemPumariumFragment("pumarium_fragment");
	public static final ItemCallaxiumFragment ITEM_CALLAXIUM_FRAGMENT = new ItemCallaxiumFragment("callaxium_fragment");
	public static final ItemSkorpiumFragment ITEM_SKORPIUM_FRAGMENT = new ItemSkorpiumFragment("skorpium_fragment");
	public static final ItemStupidiumFragment ITEM_STUPIDIUM_FRAGMENT = new ItemStupidiumFragment("stupidium_fragment");
	
	public static final ItemBaseDust ITEM_BASE_DUST = new ItemBaseDust("base_dust");
	public static final ItemOedldoedlDust ITEM_OEDLDOEDL_DUST = new ItemOedldoedlDust("oedldoedl_dust");
	public static final ItemEnderDust ITEM_ENDER_DUST = new ItemEnderDust("ender_dust");
	public static final ItemSulfurDust ITEM_SULFUR_DUST = new ItemSulfurDust("sulfur_dust");
	public static final ItemSaltpeterDust ITEM_SALTPETER_DUST = new ItemSaltpeterDust("saltpeter_dust");
	public static final ItemSaltDust ITEM_SALT_DUST = new ItemSaltDust("salt_dust");
	
	public static final ItemBaseSingularity ITEM_BASE_SINGULARITY = new ItemBaseSingularity("base_singularity");
	public static final ItemOedldoedlSingularity ITEM_OEDLDOEDL_SINGULARITY = new ItemOedldoedlSingularity("oedldoedl_singularity");
	public static final ItemGremoriumSingularity ITEM_GREMORIUM_SINGULARITY = new ItemGremoriumSingularity("gremorium_singularity");
	public static final ItemHimejimariumSingularity ITEM_HIMEJIMARIUM_SINGULARITY = new ItemHimejimariumSingularity("himejimarium_singularity");
	public static final ItemToujouriumSingularity ITEM_TOUJOURIUM_SINGULARITY = new ItemToujouriumSingularity("toujourium_singularity");
	public static final ItemArgentoriumSingularity ITEM_ARGENTORIUM_SINGULARITY = new ItemArgentoriumSingularity("argentorium_singularity");
	public static final ItemQuartariumSingularity ITEM_QUARTARIUM_SINGULARITY = new ItemQuartariumSingularity("quartarium_singularity");
	
	public static final ItemOedldoedlCatalyst ITEM_OEDLDOEDL_CATALYST = new ItemOedldoedlCatalyst("oedldoedl_catalyst");
	public static final ItemChaosCatalyst ITEM_CHAOS_CATALYST = new ItemChaosCatalyst("chaos_catalyst");
	
	public static final ItemBalancedClay ITEM_BALANCED_CLAY = new ItemBalancedClay("balanced_clay");
}